name: python-ci

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.6"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest black docformatter ruff
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Format and Lint Code
        run: |
          black .
          docformatter -i -r .
          ruff check --fix

      - name: Check for uncommitted changes
        run: |
          git diff --exit-code

      - name: Test with pytest
        run: |
          pytest

  ci:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t pooripro/thai-chai-service-api:latest .

      - name: Push Docker Image
        run: |
          docker push pooripro/thai-chai-service-api:latest
          
  cd:
    needs: cd
    runs-on: self-hosted
    
    steps:
    - name: Pull Docker image
      run: sudo docker pull pooripro/thai-chai-service-api:latest
    - name: Delete Old docker container
      run: sudo docker rm -f thai-chai-service-api-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name thai-chai-service-api-container pooripro/thai-chai-service-api